# example docker-compose file
version: '3'
services:
  lldpd:
    image: ibhde/lldpd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    hostname: myhostname
    # LLDPD options: hide kernel details and enable CDP
    command: ["-k", "-c"]
